/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from './Counter.sol/index.js';
export * as ierc20Sol from './IERC20.sol/index.js';
export * as iUniswapSol from './IUniswap.sol/index.js';